### ISSUE TITLE
connector/worker [8]

### ISSUE THREAD

**Issue by mthenw** [serverless/event-gateway-connector#4]

**Comment by sebito91** [comment]
Worker receives configuration details from the watcher and initializes connection to service (kinesis). Must able to perform the following:

1. retrieve and parse the config for service
2. test and connect to service
3. subscribe to provided topic/partition/shard
4. format message payload into `CloudEvent`
5. send payload to requisite Event Gateway
6. OPTIONAL deliver metrics to some kind of endpoint (or provide prometheus scraper)
